# base-image php:7-apache from docker hub
FROM php:7-apache
# create an environment variable TZ (timezone)
ENV TZ="Europe/Berlin"
# copy local index.php to remote (image) path
COPY index.php /var/www/html
