= docker postgres

== if you already configured docker postgres
* just start / stop the image

----
docker start postgres-image
docker stop postgres-image
----

* example connection

----
host: localhost
port: 5432 
user: postgres
database: developer-db
----

* JDBC URL

----
jdbc:postgresql://localhost:5432/developer-db
----

== psql
* psql is a terminal-based front-end to PostgreSQL.
* assumption: postgresql is running
* if you are running postgresql in container then open shell. 
----
docker exec -it postgres-image bash
----
* change user
----
su postgres
----
* run psql
----
/$ psql
----
* create database
----
postgres=# create database dev;
CREATE DATABASE
----
* create user
----
postgres=# create user dev with password 'dev';
CREATE ROLE
----
* list all databases
----
postgres=# \l
                                  List of databases
     Name     |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges   
--------------+----------+----------+------------+------------+-----------------------
 dev          | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 developer-db | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 postgres     | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 ...
----
* list schema
----
postgres=# \dn
  List of schemas
  Name  |  Owner   
--------+----------
 public | postgres
(1 row)
----
* quit psql
----
postgres=# \q
----
* connect to database
----
postgres=# \c dev dev
You are now connected to database "dev" as user "dev".
----
* create table
----
dev=> create table developers (id integer PRIMARY KEY, name varchar(40));
CREATE TABLE
----
* list table
----
dev=> \dt
          List of relations
 Schema |    Name    | Type  | Owner 
--------+------------+-------+-------
 public | developers | table | dev
(1 row)
----
* insert table
----
dev=> insert into developers values (0, 'java');
INSERT 0 1
----
* select table
----
dev=> select * from developers 
dev-> ;
 id |  name  
----+--------
  0 | java
  1 | python
  2 | cpp
(3 rows)
----

== full steps
* get latest postgres image

----
docker pull postgres
----

* run: 5432 is default postrges port. mount a volume for data persistance.

----
docker run -p 5432:5432 -v $HOME/postgres-docker:/var/lib/postgresql/data --name postgres-image postgres
----


* for log. if you start with detached: docker run -d ...

----
docker logs postgres-image
----

* open shell

----
docker exec -it postgres-image sh

# createdb -U postgres developer-db     // create a database
----

* connect to database

----
# psql -U postgres developer-db
----

* list databases

----
developer-db=# \l
                                  List of databases
     Name     |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges   
--------------+----------+----------+------------+------------+-----------------------
 developer-db | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
----

* create table

----
developer-db=# CREATE TABLE programming_languages (id int, name varchar(80));
CREATE TABLE
----

* describe a table

----
developer-db=# \d programming_languages
              Table "public.programming_languages"
 Column |         Type          | Collation | Nullable | Default 
--------+-----------------------+-----------+----------+---------
 id     | integer               |           |          | 
 name   | character varying(80) |           |          | 
----

* select table (TAB for auto complete)

----
developer-db=# select * from programming_languages ;
 id | name 
----+------
(0 rows)
----

* quit from psql

----
developer-db-# \q
----

* exit from shell, stop docker and start again

----
exit
docker stop postgres-image
docker start postgres-image
----

* clean up everthing

----
docker rm -f postrges-image
docker volume rm postgres-docker
----

